Blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from Blog.views import client, dashboard
from base import settings

app_name = "Blog"
urlpatterns = [
    path("",client.index,name="blog_index"),
    path("post_data/<str:hash_id>",client.fetch_post,name="fetch_post"),
    path("category/<str:slug>",client.category,name="category"),
    path("series/<str:slug>",client.series,name="series"),
    path("tag/<str:slug>",client.tag,name="tag"),
    path("post/<str:cat>/<str:slug>",client.view_post,name="read_post"),
    path("comment/<str:phash>/<str:chash>",client.comment,name="comment"),
    path("user/<str:username>",client.user_profile,name='user_profile'),
    path("signin",client.signin,name="signin"),
    path("signup",client.signup,name="signup"),
    path("signout",client.signout,name="signout"),
    path("verify/<str:token>",client.email_verify,name="email_verify"),
    path("reset/<str:token>",client.password_reset,name="password_reset"),
    path("about-us",client.about_us,name="about_us"),
    path("contact-us",client.contact_us,name="contact_us"),
    path("tos",client.tos,name="tos"),
    path("privacy",client.privacy,name="privacy"),
    path("projects",client.projects,name="projects"),
    
    #Dashboard
    path("dashboard",dashboard.dashboard,name="dashboard"),
    path("dashboard/view_profile",dashboard.view_profile,name="view_profile"),
    path("dashboard/edit_profile",dashboard.edit_profile,name="edit_profile"),
    path("dashboard/change_password",dashboard.change_password,name="change_password"),
    path("dashboard/post/edit/<str:hash_id>",dashboard.edit_post,name="edit_post"),
    path("dashboard/write_post",dashboard.write_post,name="write_post"),
    path("dashboard/post/list",dashboard.list_post,name="list_post"),
    path("dashboard/notifications",dashboard.notifications,name="notifications"),
    path("dashboard/notification/<str:hash_id>",dashboard.notification_link,name="notification_link"),
    path("dashboard/reports",dashboard.reports,name="reports"),
    path("dashboard/report/<str:hash_id>",dashboard.report_link,name="report_link"),
    path("dashboard/pending",dashboard.pending_post,name='pending_post'),
    path("dashboard/pending_comment",dashboard.pending_comment,name='pending_comment'),
    path("dashboard/pending_request",dashboard.pending_request,name='pending_request'),
    path("dashboard/upload-image",dashboard.upload_image,name="image-upload"),
    path("dashboard/suneditor_gallery",dashboard.suneditor_gallery,name="suneditor_gallery"),
    path("dashboard/send_request",dashboard.save_request,name="send_request"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Blog.urls")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Blog/forms.py
#import modules
from django.forms import ModelForm
from .models import *

#write model forms
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

Blog/views/client.py
#import modules
from django.shortcuts import render, redirect
from django.http import HttpResponse,Http404
from django.urls import reverse
from Blog.models import *
from taggit.models import Tag
from django.db.models import Q
from better_profanity import profanity
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from Blog.models import AuthorUser
from Blog.extrafunc import *
from Blog.token import *
import base64
import json

#home page of blog to show posts
def index(request):
    if request.method == 'POST':
        email = extract_unique_email(request.POST.get('email',None))
        if email:
            if EmailSubscribe.objects.filter(email=email).exists():
                messages.error(request,"The email you have given may already in the list.")
                return redirect(reverse('Blog:blog_index')+"#feadback")
            else:
                EmailSubscribe(email=email).save()
                messages.success(request,'Your email is successfully added to the list.')
                return redirect(reverse('Blog:blog_index')+"#feadback")
        else:
            messages.error(request,'Sorry, invalid email address.')
            return redirect(reverse('Blog:blog_index')+"#feadback")

    else:
        query = None
        if request.GET.get('query',None):
            query = request.GET.get('query',None)
            posts = Post.objects.filter(Q(status="Published")|Q(status="Hot"),Q(title__icontains=query)|Q(description__icontains=query)|Q(author__username__contains=query)|Q(category__name__contains=query)|Q(series__name__contains=query),is_deleted=False)
        else:
            posts = Post.objects.filter(Q(status="Published")|Q(status="Hot"),is_deleted=False)
    
        try:
            post_per_page = int(BlogSetting.objects.filter(setting='post-per-page').first().value)
        except:
            post_per_page = 10

        page = request.GET.get('post-page',1)
        posts_page = Paginator(posts,post_per_page,2)
        current_page = posts_page.get_page(page)
        list_page = current_page.paginator.get_elided_page_range(number=current_page.number,on_each_side=2,on_ends=1)
        return render(request,"_Blog/client/index.html",{"page":current_page,'list_page':list_page,'query':query})
   

#fetch post to be displayed in blog by jquery
def fetch_post(request,hash_id):
    if request.method == "POST":
        try:
            post = Post.objects.get(hash_id=hash_id,is_deleted=False)
            if post.author == request.user:
                return HttpResponse(post.content)
            elif post.status in ['Published','Hot']:
                return HttpResponse(post.content)
            else: 
                return HttpResponse("...")
        except:
            return HttpResponse("No valid post found with your query.")
    else:
        pass

#show posts by category
def category(request,slug):

    page = request.GET.get('post-page',1)
    try:
        post_category = Category.objects.get(slug=slug)
    except:
        raise Http404
    
    category = Category.objects.get(slug=slug).get_descendants(include_self=True)
    posts = Post.objects.filter(Q(status="Published")|Q(status="Hot"),category__in=category)
    posts_page = Paginator(posts,2)
    current_page = posts_page.get_page(page)
    list_page = current_page.paginator.get_elided_page_range(number=current_page.number,on_each_side=2,on_ends=1)
    return render(request,"_Blog/client/category_post.html",{"page":current_page,'list_page':list_page,"post_category":post_category})

#show posts by series
def series(request,slug):

    page = request.GET.get('post-page',1)
    try:
        series = Series.objects.get(slug=slug)
    except:
        raise Http404
    posts = Post.objects.filter(Q(status="Published")|Q(status="Hot"),series=series)
    posts_page = Paginator(posts,2)
    current_page = posts_page.get_page(page)
    list_page = current_page.paginator.get_elided_page_range(number=current_page.number,on_each_side=2,on_ends=1)
    return render(request,"_Blog/client/series_post.html",{"page":current_page,'list_page':list_page,'series':series})

#show posts by tags
def tag(request,slug):

    page = request.GET.get('post-page',1)
    try:
        tag = Tag.objects.get(slug=slug)
    except:
        raise Http404
    posts = Post.objects.filter(Q(status="Published")|Q(status="Hot"),tags=tag)
    posts_page = Paginator(posts,2)
    current_page = posts_page.get_page(page)
    list_page = current_page.paginator.get_elided_page_range(number=current_page.number,on_each_side=2,on_ends=1)
    return render(request,"_Blog/client/tag_post.html",{"page":current_page,'list_page':list_page,'tag':tag})
    
#sending the post instance to be rendered in details
def view_post(request,cat,slug):
    try:
        category = Category.objects.get(slug=cat)
    except:
        category = None
    user = request.user if request.user.is_authenticated else None
    try:
        if request.user == "Admin" or request.user.is_superuser:
            post = Post.objects.get(category=category,slug=slug)
        else:
            post = Post.objects.get(category=category,slug=slug,is_deleted=False)
    except:
        raise Http404('No post found.')
    
    if post.status not in ['Published','Hot'] and post.author == user:
        messages.success(request,"This post preview just for you nobody else can see that until this is published.")
    elif post.status in ['Published','Hot']:
        pass
    elif user.rank == 'Admin' or user.is_superuser:
        messages.success(request,'You are able to view the post because of your rank.')
    else:
        raise Http404('No post found.')
    
    if request.method == "POST":
        if not request.user.is_authenticated:
            return HttpResponse(json.dumps({'success':False,'msg':'You are not logged in.'}))
        
        referer_url = request.META['HTTP_REFERER']
        liked = request.POST.get('liked',False)
        disliked = request.POST.get('disliked',False)
        report_content = request.POST.get('report_content',None)
        if liked:
            post.like.add(request.user)
            return HttpResponse(json.dumps({'success':True,'status':'liked'}))
        elif disliked:
            post.like.remove(request.user)
            post.dislike.add(request.user)
            return HttpResponse(json.dumps({'success':True,'status':'disliked'}))
        
        if report_content and len(report_content) >= 6:
            if request.user != post.author:
                ReportContent.objects.create(type='Post',content_type=ContentType.objects.get_for_model(Post),content_id=post.pk,report_by=request.user,report_content=report_content)
                messages.success(request,"Your report has been sent to admin. and you will get notified when the issue will be solved.")
                return redirect(f"{referer_url}#feadback")
            else:
                messages.success(request,"Why you should report your own post?")
                return redirect(f"{referer_url}#feadback")
        
        messages.success(request,"Seems invalid post request.")
        return redirect(f"{referer_url}#feadback")

    else:
        page_number = int(request.GET.get('comment_page',1))
        comments = Comment.objects.filter(post=post,is_deleted=False,level=0,status="Published").order_by('-date')
        try:
            comment_per_page = (BlogSetting.objects.filter(setting='comment-per-page').first().value)
        except:
            comment_per_page = 10
        comment_paginator = Paginator(comments,comment_per_page,2)
        comment_page = comment_paginator.get_page(page_number)
        series = post.series.name if post.series else ''
        related_post = Post.objects.filter(Q(status="Published")|Q(status="Hot"),Q(title__icontains=post.title)|Q(description__icontains=post.description)|Q(category__name__contains=post.category.name)|Q(series__name__contains=series),is_deleted=False).exclude(pk=post.pk)[:4]
        return render(request,"_Blog/client/read_post.html",{'post':post,'related_post':related_post,'comment_page':comment_page,})
   
#Comment handler
def comment(request,phash,chash):
    #Initializing variables
    referer_url = request.META['HTTP_REFERER']
    user = request.user if request.user.is_authenticated else None
    
    try:
        post = Post.objects.filter(Q(status='Published')|Q(status='Hot'),hash_id=phash,is_deleted=False)[0]
    except:
        messages.error(request,"No published post found to comment.")
        return redirect(f"{referer_url}#feadback")
    
    if chash == '0':
        comment = None
    else:
        try:
            comment = Comment.objects.filter(hash_id=chash,post=post)[0]
        except:
            messages.error(request,"No comment found with the id.")
            return redirect(f"{referer_url}#feadback")

    

    if request.method == "POST":
        report_content = request.POST.get("report",None)
        comment_content = request.POST.get("comment",None)
        comment_delete = request.POST.get("comment_delete",None)
        comment_edit = request.POST.get("comment_edit",None)
        if report_content: #Handling comment report if it's in post form
            if user and user != comment.commenter:
                if 1 > len(report_content) > 255:
                    messages.error(request,"Your report is have to more than single character & less than 255.")
                    return redirect(f"{referer_url}#feadback")
                elif not comment.commenter:

base/views.py
#importing modules
from django.shortcuts import render
from django.http import HttpResponse


#view function

base/templates/_Blog/client/about_us.html
{% extends "_Blog/client/home_layout.html" %}
{% load static %}
{% load blog_tags %}
{% block title %} About us {% endblock %}
{% block description %}     Welcome to DevSecBBS! We are a collaborative platform where passionate writers and experts come together to share valuable insights and information. Our mission is to empower individuals by providing a diverse and inclusive space for knowledge exchange. With engaging content, expert contributors, and a vibrant community, we invite you to join us on this journey of learning, growth, and connection. Contact us for any inquiries or to contribute to our blog. Thank you for visiting DevSecBBS.
{% endblock %}

{% block body %}

<p class="mb-3 text-gray-500 dark:text-gray-400">
    Welcome to DevSecBBS! We are a collaborative platform where passionate writers and experts come together to share valuable insights and information. Our mission is to empower individuals by providing a diverse and inclusive space for knowledge exchange. With engaging content, expert contributors, and a vibrant community, we invite you to join us on this journey of learning, growth, and connection. Contact us for any inquiries or to contribute to our blog. Thank you for visiting DevSecBBS.
</p>

{% endblock %}

base/templates/_Blog/client/privacy.html
{% extends "_Blog/client/home_layout.html" %}
{% load static %}
{% load blog_tags %}
{% block title %} Privacy Policy {% endblock %}
{% block description %}     Welcome to DevSecBBS! We are a collaborative platform where passionate writers and experts come together to share valuable insights and information. Our mission is to empower individuals by providing a diverse and inclusive space for knowledge exchange. With engaging content, expert contributors, and a vibrant community, we invite you to join us on this journey of learning, growth, and connection. Contact us for any inquiries or to contribute to our blog. Thank you for visiting DevSecBBS.
{% endblock %}

{% block body %}

<p class="mb-3 text-gray-500 dark:text-gray-400">
    At DevSecBBS, we take your privacy seriously. We collect and store personal information, such as your name and email address, only when voluntarily provided by you. This information is used to improve your experience on our blog and to communicate with you regarding updates and new content. We do not share your personal information with third parties unless required by law. We use cookies to enhance your browsing experience, but you can disable them in your browser settings if you prefer. We take appropriate measures to protect your personal information, but please note that no method of transmission over the internet is completely secure. By using DevSecBBS, you consent to the terms of this Privacy Policy.
</p>

{% endblock %}

base/templates/_Blog/client/signup.html
{% extends "_Blog/client/core_layout.html" %}
{% load static %}
{% load blog_tags %}
{% block title %} Home {% endblock %}
{% block description %} This is DecSecBBS is the only blog the on the earth about technology {% endblock %}


{% block body %}

<section class="bg-gray-50 dark:bg-gray-900 p-24">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <a href="{% url 'Blog:blog_index' %}" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
            <img class="w-8 h-8 mr-2" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg" alt="logo">
            DevSecBBS
        </a>
        <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                    Create and account
                </h1>
                
                <!-- Django message handler -->
                <div id="feadback" class="no-target">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div id="success-{{forloop.counter}}" class="flex p-4 mb-4 text-green-800 rounded-lg bg-green-50 dark:bg-gray-600 dark:text-green-400" role="alert">
                            <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                            <span class="sr-only">Info</span>
                            <div class="ml-3 text-sm font-medium">
                            {{message}}
                            </div>
                            <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-green-50 text-green-500 rounded-lg focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-gray-700" data-dismiss-target="#success-{{forloop.counter}}" aria-label="Close">
                                <span class="sr-only">Close</span>
                                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                            </button>
                        </div>
                    {% elif message.tags == 'error' %}
                        <div id="info-{{forloop.counter}}" class="flex p-4 mb-4 text-red-800 rounded-lg bg-red-50 dark:bg-gray-600 dark:text-red-400" role="alert">
                            <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                            <span class="sr-only">Info</span>
                            <div class="ml-3 text-sm font-medium">
                            {{message}}
                            </div>
                            <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-red-50 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex h-8 w-8 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700" data-dismiss-target="#info-{{forloop.counter}}" aria-label="Close">
                            <span class="sr-only">Close</span>
                            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                            </button>
                        </div>
                    {% endif %}
                    {% endfor %}
                </div>
                <!-- End django message handler -->

                <form class="space-y-4 md:space-y-6" action="{% url 'Blog:signup' %}" method="POST">
                    {% csrf_token %}
                    <div>
                        <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                        <input type="text" name="username" id="username" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="bob404" required="">
                    </div>
                    <div>
                        <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
                        <input type="email" name="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required="">
                    </div>
                    <div>
                        <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                        <input type="password" name="password" id="password" placeholder="••••••••••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                        <p class="flex items-center text-sm text-gray-500 dark:text-gray-400">Password rules (HarDP@44wor!) <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="w-4 h-4 ml-2 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show rules</span></button></p>
                        <div data-popover id="popover-description" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                            <ul class="max-w-md space-y-1 p-2 text-gray-500 list-disc list-inside dark:text-gray-400">
                                <li>Minimum length of 8 characters</li>
                                <li>Contains at least one lowercase letter</li>
                                <li>Contains at least one UPPERCASE letter</li>
                                <li>Contains at least 1 digit</li>
                                <li>Contains at least one special character. (e.g., !@#$%^&*)</li>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <label for="confirm-password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirm password</label>
                        <div class="flex">
                            <input type="password" name="confirm-password" id="confirm-password" placeholder="••••••••••••••••" class="rounded-l-md bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
                            <span id="password-view" class="cursor-pointer inline-flex hover:bg-gray-400 items-center px-3 text-sm text-gray-900 rounded-none rounded-r-lg bg-gray-200 border border-r-0 border-gray-300 dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                                <svg viewBox="0 0 24 24" class="w-4 h-4 text-gray-500 dark:text-gray-400" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <circle cx="12" cy="12" r="3.5" stroke="currentColor"></circle> <path d="M20.188 10.9343C20.5762 11.4056 20.7703 11.6412 20.7703 12C20.7703 12.3588 20.5762 12.5944 20.188 13.0657C18.7679 14.7899 15.6357 18 12 18C8.36427 18 5.23206 14.7899 3.81197 13.0657C3.42381 12.5944 3.22973 12.3588 3.22973 12C3.22973 11.6412 3.42381 11.4056 3.81197 10.9343C5.23206 9.21014 8.36427 6 12 6C15.6357 6 18.7679 9.21014 20.188 10.9343Z" stroke="currentColor"></path> </g></svg>
                            </span>
                        </div>
                    </div>
                    <div class="flex items-start">
                        <div class="flex items-center h-5">
                          <input id="terms" aria-describedby="terms" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800" required="">
                        </div>
                        <div class="ml-3 text-sm">
                          <label for="terms" class="font-light text-gray-500 dark:text-gray-300">I accept the <a class="font-medium text-blue-600 hover:underline dark:text-blue-500" href="{% url 'Blog:tos' %}">Terms and Conditions</a></label>
                        </div>
                    </div>
                    <button id="submit-form" class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" disabled>Create an account</button>
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        Already have an account? <a href="{% url 'Blog:signin' %}" class="font-medium text-blue-600 hover:underline dark:text-blue-500">Signin here</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}
{% block script %}
    <script src="{% static "_Blog/script/client/registration.js" %}"></script>
{% endblock %}