Blog/urls.py
from django.urls import path
from django.conf.urls.static import static
from Blog.views import client, dashboard
from base import settings

app_name = "Blog"
urlpatterns = [
    path("",client.index,name="blog_index"),
    path("post_data/<str:hash_id>",client.fetch_post,name="fetch_post"),
    path("category/<str:slug>",client.category,name="category"),
    path("series/<str:slug>",client.series,name="series"),
    path("tag/<str:slug>",client.tag,name="tag"),
    path("post/<str:cat>/<str:slug>",client.view_post,name="read_post"),
    path("comment/<str:phash>/<str:chash>",client.comment,name="comment"),
    path("user/<str:username>",client.user_profile,name='user_profile'),
    path("signin",client.signin,name="signin"),
    path("signup",client.signup,name="signup"),
    path("signout",client.signout,name="signout"),
    path("verify/<str:token>",client.email_verify,name="email_verify"),
    path("reset/<str:token>",client.password_reset,name="password_reset"),
    path("about-us",client.about_us,name="about_us"),
    path("contact-us",client.contact_us,name="contact_us"),
    path("tos",client.tos,name="tos"),
    path("privacy",client.privacy,name="privacy"),
    path("projects",client.projects,name="projects"),
    
    #Dashboard
    path("dashboard",dashboard.dashboard,name="dashboard"),
    path("dashboard/view_profile",dashboard.view_profile,name="view_profile"),
    path("dashboard/edit_profile",dashboard.edit_profile,name="edit_profile"),
    path("dashboard/change_password",dashboard.change_password,name="change_password"),
    path("dashboard/post/edit/<str:hash_id>",dashboard.edit_post,name="edit_post"),
    path("dashboard/write_post",dashboard.write_post,name="write_post"),
    path("dashboard/post/list",dashboard.list_post,name="list_post"),
    path("dashboard/notifications",dashboard.notifications,name="notifications"),
    path("dashboard/notification/<str:hash_id>",dashboard.notification_link,name="notification_link"),
    path("dashboard/reports",dashboard.reports,name="reports"),
    path("dashboard/report/<str:hash_id>",dashboard.report_link,name="report_link"),
    path("dashboard/pending",dashboard.pending_post,name='pending_post'),
    path("dashboard/pending_comment",dashboard.pending_comment,name='pending_comment'),
    path("dashboard/pending_request",dashboard.pending_request,name='pending_request'),
    path("dashboard/upload-image",dashboard.upload_image,name="image-upload"),
    path("dashboard/suneditor_gallery",dashboard.suneditor_gallery,name="suneditor_gallery"),
    path("dashboard/send_request",dashboard.save_request,name="send_request"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Blog.urls")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Blog/views/dashboard.py
#import modules
from django.shortcuts import render, redirect
from django.http import HttpResponse,Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse
from Blog.models import *
from PIL import Image
import json
from taggit.models import Tag
import datetime
from django.db.models import Q
import os
from django.contrib import messages
from django.core.paginator import Paginator
from Blog.extrafunc import *
from Blog.token import *
import requests as rq
import base64


#User dashboard
@login_required
def dashboard(request):
    published_post = Post.objects.filter(Q(status='Published')|Q(status='Hot'),author=request.user)
    liked = Post.objects.filter(like__in=[request.user])
    following = request.user.user_following.all()
    try:
        notice = BlogSetting.objects.filter(setting='notice').first().value
    except:
        notice = ''

    context = {
        'published_post':published_post,
        'liked':liked,
        'following':following,
        'notice': notice
    }
    return render(request,'_Blog/dashboard/dashboard.html',context)

#Listing the post owned by user in dashboard
@login_required
def list_post(request):
    if request.method == "POST":
        page_number = int(request.GET.get('page',1))
        query = request.POST.get('query',None)

        if request.user.is_superuser or request.user.rank == "Admin":
            post = Post.objects.filter(Q(title__contains=query)|Q(description__contains=query)|Q(status__contains=query)|Q(slug__contains=query)|Q(category__name__contains=query))
        else:
            post = Post.objects.filter(Q(title__contains=query)|Q(description__contains=query)|Q(status__contains=query)|Q(slug__contains=query)|Q(category__name__contains=query),is_deleted=False,author=request.user)

        if post:
            page_number = int(request.GET.get('page',1))
            paginator = Paginator(post,len(post))
            page = paginator.get_page(page_number)
            list_page = page.paginator.get_elided_page_range(number=page.number,on_each_side=2,on_ends=1)
            return render(request,"_Blog/dashboard/list_post.html",{'page':page,'list_page':list_page})
        else:
            return render(request,"_Blog/dashboard/list_post.html",{'page':None,'list_page':None,'query':'Not found'})
    else:
        page_number = int(request.GET.get('page',1))
        if request.user.is_superuser or request.user.rank == "Admin":
            post = Post.objects.filter()
        else:
            post = Post.objects.filter(is_deleted=False,author=request.user)
        paginator = Paginator(post,10,3)
        page = paginator.get_page(page_number)
        list_page = page.paginator.get_elided_page_range(number=page.number,on_each_side=2,on_ends=1)
        return render(request,"_Blog/dashboard/list_post.html",{'page':page,'list_page':list_page})

#validating & saving written post
@login_required
@for_banned_user
def write_post(request):
    if request.method == "POST":

        title = request.POST.get('title','')
        description = request.POST.get('description','')
        cover_photo = request.FILES.get('cover_photo',None)
        content = request.POST.get('content',None)
        status = request.POST.get('status',"Draft")
        author = request.user
        tags = tuple(request.POST.getlist('tags',()))

        if request.user.rank == 'Contributor':
            if status == "Published":
                status = 'Pending'
            else:
                pass
        try:
            category = Category.objects.get(hash_id=request.POST.get('category',None))
        except Exception as error:
            response = {"status":"error","message":"Unable to find category you selected!"}
            return HttpResponse(json.dumps(response)) 

        try:
            series = Series.objects.get(hash_id=request.POST.get('series',None))
            if series in request.user.series.all():
                series = series
        except:
            series = None
            
        if 5 > len(title):
            return HttpResponse(json.dumps({"status":"error","message":"Your post title should not be too short or more than 255 character."}))
        elif len(title) > 254:
            return HttpResponse(json.dumps({"status":"error","message":"Your post title is too long."}))
        elif cover_photo:
            try:
                Image.open(cover_photo)
            except:
                return HttpResponse(json.dumps({"status":"error","message":"Thanks for try to upload not an image or any payload."}))
        elif not cover_photo and author.rank in ['Contributor','Banned']:
            return HttpResponse(json.dumps({"status":"error","message":"Where is the cover image?"}))
        elif not category:
            return HttpResponse(json.dumps({"status":"error","message":"Did you forgot to categorize your post!"}))
        elif not content:
            return HttpResponse(json.dumps({"status":"error","message":"Your forgot your aim. Where to the content?"}))
        elif len(description) > 255 :
            return HttpResponse(json.dumps({"status":"error","message":"Your post description should not be more than 255 character."}))
        elif not status in ['Draft','Published','Pending']:
            return HttpResponse(json.dumps({"status":"error","message":"Your selected post status is not seems valid."}))
        else:
            pass
        
        new_post = Post.objects.create(title=title,description=description,series=series,cover_photo=cover_photo,content=content,category=category,author=author,status=status)
        new_post.tags.add(*tags)
        new_post.save()
        
        edit_post_url = root_url(request) +str(reverse('Blog:edit_post', args = [new_post.hash_id] ))
        response = {"status":"success","message":"Post has been saved successfully",'destination':edit_post_url}
        # Resize and reduce the image size
        try:
            image_path = new_post.cover_photo.path
            resize_image(image_path,output_size=(600,300))
        except:
            pass
        return HttpResponse(json.dumps(response))
    else:
        category = Category.objects.filter(level=0)
        tags = Tag.objects.all()
        return render(request,'_Blog/dashboard/write_post.html',{'category':category,'tags':tags})

#Post edit
@login_required
@for_banned_user
def edit_post(request,hash_id):

    try:
        if request.user.is_superuser or request.user.rank == "Admin":
            _post = Post.objects.get(hash_id=hash_id)
        else:
            _post = Post.objects.get(hash_id=hash_id,is_deleted=False,author=request.user)
    except:
        raise Http404


    if request.method == "POST":
        
        is_delete = request.POST.get('delete',False)
        if is_delete == 'true':
            _post.is_deleted = True
            _post.save()
            messages.success(request,f"Your post titled '{_post.title}' has been deleted.")
            return redirect(reverse('Blog:list_post'))
        
        if _post.status == 'Pending':
            return HttpResponse(json.dumps({"status":"error","message":"While your post are pending under review. You can't make any change for now. Not even by manupulate the request."}))
        elif _post.status == 'Rejected':
            return HttpResponse(json.dumps({"status":"error","message":"While your post are rejected. Please improve that for being accepted."}))

        title = request.POST.get('title','')
        description = request.POST.get('description','')
        cover_photo = request.FILES.get('cover_photo',None)
        content = request.POST.get('content',None)
        status = request.POST.get('status',"Draft")
        author = request.user
        tags = tuple(request.POST.getlist('tags',()))
        feadback_msg = None

        if request.user.rank == 'Contributor':
            if status == "Published":
                status = 'Pending'
                feadback_msg = "Your post has been successfully edited & under review. You will get notified about status after review."
            else:
                pass 
        
        try:
            category = Category.objects.get(hash_id=request.POST.get('category',None))
        except:
            response = {"status":"error","message":"Unable to find category you selected!"}
            return HttpResponse(json.dumps(response)) 

        try:
            series = Series.objects.get(hash_id=request.POST.get('series',None))
            if series in request.user.series.all():
                series = series
        except:
            series = None   

        
        if 5 > len(title) :
            return HttpResponse(json.dumps({"status":"error","message":"Your post title should not be too short or more than 255 character."}))
        elif cover_photo:
            try:
                Image.open(cover_photo)
            except:
                return HttpResponse(json.dumps({"status":"error","message":"Thanks for try to upload not an image or any payload."}))
        elif (not cover_photo and not _post.cover_photo) and author.rank in ['Contributor','Banned']:
            return HttpResponse(json.dumps({"status":"error","message":"Where is the cover image?"}))
        elif not category:
            return HttpResponse(json.dumps({"status":"error","message":"Did you forgot to categorize your post!"}))
        elif not content:
            return HttpResponse(json.dumps({"status":"error","message":"Your forgot your aim. Where to the content?"}))
        elif len(description) > 255 :
            return HttpResponse(json.dumps({"status":"error","message":"Your post description should not be more than 255 character."}))

base/views.py
#importing modules
from django.shortcuts import render
from django.http import HttpResponse


#view function

base/templates/_Blog/dashboard/pending_item/pending_comment.html
{% extends "_Blog/dashboard/dashboard_layout.html" %}
{% load static %}
{% load blog_tags %}
{% block title %} List Pending Request {% endblock %}



{% block body %}


<!-- Start request pending tab  -->
<h1 class="mb-4 py-4 text-center text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-2xl lg:text-6xl dark:text-white">Pending : all the request those are pending.</h1>
<div class="border-b border-gray-200 dark:border-gray-700 dark:bg-gray-700 mb-1">
    <ul class="flex flex-wrap -mb-px text-sm font-medium text-center text-gray-500 dark:text-gray-400">
        <li class="mr-2">
            <a href="{% url 'Blog:pending_post' %}" class="inline-flex p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 group">
                <svg class="w-5 h-5 mr-2 text-gray-400 group-hover:text-gray-500 dark:text-gray-500 dark:group-hover:text-gray-300" version="1.1" id="_x32_" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <style type="text/css"> .st0{fill:#000000;} </style> <g> <rect x="106.667" y="106.667" class="st0" width="298.666" height="106.666"></rect> <path class="st0" d="M0,0v512h512V0H0z M458.667,458.667H53.333V53.333h405.334V458.667z"></path> <rect x="256" y="277.333" class="st0" width="149.333" height="32"></rect> <rect x="256" y="362.667" class="st0" width="149.333" height="32"></rect> <rect x="106.667" y="277.333" class="st0" width="106.666" height="117.334"></rect> </g> </g></svg> Post  
            </a>
        </li>
        <li class="mr-2">
            <a href="{% url 'Blog:pending_comment' %}" class="inline-flex dark:bg-gray-600 bg-gray-100 dark:text-white text-gray-900 p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 group">
                <svg class="w-5 h-5 mr-2 text-gray-400 group-hover:text-gray-500 dark:text-gray-500 dark:group-hover:text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 24 24"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M21.99 4c0-1.1-.89-2-1.99-2H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h14l4 4-.01-18zM18 14H6v-2h12v2zm0-3H6V9h12v2zm0-3H6V6h12v2z"></path></g></svg>Comment
            </a>
        </li>
        <li class="mr-2">
            <a href="{% url 'Blog:pending_request' %}" class="inline-flex p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300 group">
                <svg class="w-5 h-5 mr-2 text-gray-400 group-hover:text-gray-500 dark:text-gray-500 dark:group-hover:text-gray-300" fill="#000000" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M15.5 3.5c-7.18 0-13 5.82-13 13s5.82 13 13 13 13-5.82 13-13-5.82-13-13-13zM15.5 23.875c-0.829 0-1.5-0.672-1.5-1.5s0.671-1.5 1.5-1.5c0.828 0 1.5 0.672 1.5 1.5s-0.672 1.5-1.5 1.5zM17 17.375c0 0.828-0.672 1.5-1.5 1.5-0.829 0-1.5-0.672-1.5-1.5v-7c0-0.829 0.671-1.5 1.5-1.5 0.828 0 1.5 0.671 1.5 1.5v7z"></path> </g></svg>Request
            </a>
        </li>
    </ul>
</div>

<!-- End request pending tab -->

{% if page %}
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full min-w-64 overflow-x-auto text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3 text-center">
                    Post Title
                </th>
                <th scope="col" class="px-6 py-3">
                    Of Comment
                </th>
                <th scope="col" class="px-6 py-3">
                    To Reply
                </th>
                <th scope="col" class="px-6 py-3">
                    By
                </th>
                <th scope="col" class="px-6 py-3">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            {% for comment in page reversed %}
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" class="flex items-center px-6 py-4">
                    <img class="w-10 h-10" src="{% if comment.post.cover_photo %} {{ comment.post.cover_photo.url }} {% else %} https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg {% endif %}" alt="Jese image">
                    <div class="pl-3">
                        <div class="text-base font-semibold"><a href="{{ comment.page_of_comment }}">{{comment.post.title|slice:':250'}}</a></div>
                    </div>  
                </th>
                <td class="px-6 py-4">
                    {{ comment.parent.content|html_trunc:100 }}
                </td>
                <td class="px-6 py-4">
                    {{ comment.content }} <br>- {{comment.pk}}
                </td>
                <td class="px-6 py-4">
                    {% if comment.commenter %}
                        <a href="{% url 'Blog:user_profile' comment.commenter.username %}">{{comment.commenter.username}}</a>
                    {% else %}
                        Anonymouse
                    {% endif %}
                    </td>
                <td class="px-6 py-4">
                    <button data-modal-target="comment-modal" data-comment-hashid="{{comment.hash_id.hex}}" data-modal-toggle="comment-modal" class="response_comment text-white response_report bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        Review comment
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <nav class="flex items-center mb-2 justify-between pt-4" aria-label="Table navigation">
        <span class="text-sm font-normal ml-4 text-gray-500 dark:text-gray-400">
            Showing <span class="font-semibold text-gray-900 dark:text-white">{{ page.start_index }}-{% if page.end_index > page.paginator.count %}{{ page.paginator.count }}{% else %}{{ page.end_index }}{% endif %}</span> of <span class="font-semibold text-gray-900 dark:text-white">{{ page.paginator.count }}</span></span>
        
        {% if page.has_other_pages %}
        <ul class="inline-flex items-center mb-2 mr-2 -space-x-px">
            {% if page.has_previous %}
            <li>
                <a href="?page={{page.previous_page_number}}" class="block px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <span class="sr-only">Previous</span>
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                </a>
            </li>
            {% endif %}
            {% for page_number in list_page %}
                {% if page_number == page.paginator.ELLIPSIS %}
                <li>
                    <a href="#" disabled class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{page_number}}</a>
                </li>
                {% elif page_number == page.number %}
                    <li>
                        <a href="#" aria-current="page" class="z-10 px-3 py-2 leading-tight text-blue-600 border border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">{{page_number}}</a>
                    </li>
                {% else %}
                    <li>
                        <a href="?page={{page_number}}" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{page_number}}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <li>
                <a href="?page={{page.next_page_number}}" class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <span class="sr-only">Next</span>
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                </a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </nav>
</div>
{% else %}

<div class="p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-gray-800 dark:text-blue-400" role="alert">
    <span class="font-medium">...</span>There are have no pending comment.
</div>

{% endif %}

<!-- Start post review modal -->
<div id="comment-modal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-hide="comment-modal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="px-6 py-6 lg:px-8">
                <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">Review the comment</h3>
                <form class="space-y-6" action="{% url 'Blog:pending_comment' %}" method="POST" id="post_reponse">
                    {% csrf_token %}
                    <input type='hidden' name='comment_hash_id'>
                <div>
                    <label for="status" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select Status</label>
                    <select id="status" name='status' class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <option selected>Choose status</option>
                        <option value="Published" selected>Published</option>
                        <option value="Rejected">Rejected</option>
                    </select>
                </div>
                <div>
                    <label for="reason" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your message</label>
                    <textarea id="reason" rows="4" name='reason' class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Write your thoughts here..."></textarea>
                </div>
                <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Done review</button>
                    
                </form>
            </div>
        </div>
    </div>
</div> 
<!-- End post review modal -->

{% endblock %}
{% block script %}
<script>
    $('.response_comment').on('click',function(e){
        comment_id = $(this).data('comment-hashid')
        $('input[name="comment_hash_id"]').val(comment_id)
    })
</script>
{% endblock %}